[package]
name = "pipe"
version = "0.1.0"
authors = ["seb"]

[dependencies]
rustyline = "*"
readline  = { git = "https://github.com/shaleh/rust-readline.git"  }
rl-sys = "*"
mockers_macros = "0.5.8"

[lib]
name = "pipe"
path = "src/lib.rs"

[dev-dependencies]
mockers = "0.5.8"
stainless = "*"
